# Generated by Django 5.0.1 on 2024-01-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_active_book_author_book_pages_book_photo_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='titel',
            field=models.CharField(default=-1.0, max_length=250),
            preserve_default=False,
        ),
    ]
